chore: migrated, and linted, initial sync script files
molgenis/molgenis-py-bbmri-eric pull request #10
Opened 2021-06-11 08:34 UTC by jelmerveen

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] Updated CHANGELOG.md

2021-06-15 10:29 UTC, tommydeboer requested changes

2021-06-15 10:29 UTC, tommydeboer commented on src/molgenis/bbmri_eric/bbmri_client.py
> +                raise ValueError(exception)
Why are you wrapping this error?

2021-06-16 14:05 UTC, tommydeboer requested changes

2021-06-16 14:05 UTC, tommydeboer commented on src/molgenis/bbmri_eric/eric.py
> +        national_nodes=args.external_national_nodes,
I don't think this will work because the `BbmriSession` requires a list of dictionaries for the `national_nodes` parameter. Also see my comment about the Enum with node-url pairs. Let's discuss tomorrow.

2021-06-17 08:39 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +class BbmriSession(Session):
doesn't class method encase it with __ like __init__?

2021-06-17 08:39 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +            validate_national_node(node)
yes, that's a typo. i'll fix

2021-06-17 08:40 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +        return {"data": entity_data, "name": entity_name, "ids": entity_ids}
yes, will do

2021-06-17 08:40 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +    ) -> list[dict]:
allright, didn't know that

2021-06-17 08:41 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +        """
yes used pylint, because I didn't know back then

2021-06-17 08:41 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +                raise ValueError(exception)
allright.

2021-06-17 08:42 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_client.py
> +    def import_national_node_to_eric_entity(self, national_node_code, entity_name):
yes, exactly what I wanted to do. more procedural way of handling

2021-06-17 08:42 UTC, jelmerveen commented on src/molgenis/bbmri_eric/bbmri_validations.py
> +]
these are not urls, these are the prefixes for all staging areas on the host server

2021-06-17 08:43 UTC, jelmerveen commented on src/molgenis/bbmri_eric/eric.py
> +        national_nodes=args.external_national_nodes,
can merge the two indeed. I'll make a dataclass

2021-06-17 08:57 UTC, tommydeboer commented on src/molgenis/bbmri_eric/bbmri_client.py
> +class BbmriSession(Session):
That's for Python's internal methods that you get with every class. `__init__()`, `__str__`(), `__eq__`(), etc.

2021-06-22 07:34 UTC, tommydeboer commented on src/molgenis/bbmri_eric/bbmri_client.py
> +                raise ValueError(exception)
As discussed, we will pick this up in a separate PR

2021-06-22 08:03 UTC, tommydeboer commented on src/molgenis/bbmri_eric/bbmri_client.py
> +    def import_national_node_to_eric_entity(self, national_node_code, entity_name):
added a TODO to resolve later

2021-06-22 08:12 UTC, tommydeboer approved these changes

2021-06-22 08:12 UTC, merged