feat: add new categories
molgenis/molgenis-py-bbmri-eric pull request #106
Opened 2024-03-22 07:55 UTC by dtroelofsprins

#### Checklist
- [x] Functionality works & meets specifications
- [x] Code reviewed
- [x] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [x] Updated CHANGELOG.md

2024-03-22 07:56 UTC, dtroelofsprins commented
![](https://github.trello.services/images/mini-trello-icon.png) [#10748 Add derivation of new categories to the publish script](https://trello.com/c/hMCaEYMP/1695-10748-add-derivation-of-new-categories-to-the-publish-script)

2024-03-22 09:28 UTC, esthervanenckevort requested changes

2024-03-22 09:28 UTC, esthervanenckevort commented on src/molgenis/bbmri_eric/categories.py
>      "urn:miriam:icd:U07.2",
This is outside the change, but I noticed that this isn't the complete list of COVID-19 related terms. U07.1, U08, U09. U09.9, U10, U10.9, U11, U11.9, U12, U12.9 are also COVID19 related

2024-03-28 08:03 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/categories.py
>      "urn:miriam:icd:U07.2",
Most of them were already there (I think you've overlooked them as the file was not fully shown), but I've added U09.9, U10.9, U11.9 and U12.9

2024-04-09 12:01 UTC, esthervanenckevort approved these changes
Approved when the K5190 code has been resolved

2024-05-02 04:57 UTC, merged