Fix issue #61, import of NL data fails due to self-referencing columns
molgenis/molgenis-py-bbmri-eric pull request #62
Opened 2022-03-01 10:54 UTC by dtroelofsprins

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] Updated CHANGELOG.md

2022-03-01 11:08 UTC, dtroelofsprins commented
![](https://github.trello.services/images/mini-trello-icon.png) [BBMRI-ERIC publishing issues](https://trello.com/c/InVzgSc6/642-bbmri-eric-publishing-issues)

2022-03-02 15:20 UTC, tommydeboer requested changes

2022-03-02 15:20 UTC, tommydeboer commented on src/molgenis/bbmri_eric/bbmri_client.py
> +        if self_references and entities:
You can also add a check if `len(entities) > 1000` here

2022-03-02 15:20 UTC, tommydeboer commented on src/molgenis/bbmri_eric/utils.py
> +    )
If I understand correctly you want to get the overlap between `self_references` and the columns in `df`. You have found a clever solution! But since you are working with sets, I think you can also use an intersection:

```python
ref_columns = set(self_references).intersection(df.columns)
```

2022-03-02 15:20 UTC, tommydeboer commented on src/molgenis/bbmri_eric/utils.py
> +            if row[column] != row[column]:
🤔 🤔 🤔

2022-03-03 07:32 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/bbmri_client.py
> +        self, entity_type_id: str, self_references: List, entities: List[dict]
Fixed

2022-03-03 07:33 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/utils.py
> +def sort_self_references(rows: List[dict], self_references: List) -> List[dict]:
Done

2022-03-03 07:34 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/bbmri_client.py
> +        if self_references and entities:
Done

2022-03-03 07:34 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/bbmri_client.py
> +        if self_references and entities:
Done

2022-03-03 07:35 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/bbmri_client.py
> +        self, entity_type_id: str, self_references: List, entities: List[dict]
Done

2022-03-03 07:55 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/utils.py
> +    )
Yes, that's right, because in some cases when all entities in the list of entities have f.e. no parent collection, this column is not present in df. And in that case the sort will fail. I've used this also in the eucan-script (found it on the internet), but this is much simpler and it works fine too!

2022-03-04 06:21 UTC, dtroelofsprins commented on tests/test_utils.py
> +def test_sort_self_references():
More rows added

2022-03-14 08:10 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/utils.py
> +            if row[column] != row[column]:
Added the helper function isnan to utils.py

2022-03-14 08:36 UTC, jelmerveen approved these changes

2022-03-14 08:43 UTC, jelmerveen approved these changes

2022-03-14 09:24 UTC, jelmerveen approved these changes

2022-03-14 09:25 UTC, merged