BBMRI model changes part1 (a.o. also_known_in and head info to persons)
molgenis/molgenis-py-bbmri-eric pull request #79
Opened 2022-11-14 10:23 UTC by dtroelofsprins

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] Updated CHANGELOG.md

2022-11-14 11:14 UTC, dtroelofsprins commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite test node_data in molgenis-py-bbmri-eric tests](https://trello.com/c/0AW6mmYv/1068-rewrite-test-nodedata-in-molgenis-py-bbmri-eric-tests)

2022-11-16 10:25 UTC, tommydeboer requested changes

2022-11-16 10:25 UTC, tommydeboer commented on src/molgenis/bbmri_eric/model_fitting.py
> +    def _move_heads_for_table(self, table: Table):
The [cognitive complexity](https://docs.codeclimate.com/docs/cognitive-complexity#:~:text=Cognitive%20Complexity%20is%20a%20measure,be%20to%20read%20and%20understand.) of this method is quite high. I'll add some tips on how you can reduce it

2022-11-16 10:25 UTC, tommydeboer commented on src/molgenis/bbmri_eric/model_fitting.py
> +            if not set(row.keys()).isdisjoint(set(head_columns)):
By inverting this statement you can reduce all following code by one indentation (and it also makes the statement easier to understand):

```python
if set(row.keys()).isdisjoint(set(head_columns)):
    continue
```

This is called a [guard clause](https://deviq.com/design-patterns/guard-clause)

2022-11-16 10:25 UTC, tommydeboer commented on src/molgenis/bbmri_eric/model_fitting.py
> +                        f"{table.type.value.capitalize()[:-1]} has an head ID. "
```suggestion
                        f"{table.type.value.capitalize()[:-1]} has a head ID. "
```

2022-11-16 10:25 UTC, tommydeboer commented on src/molgenis/bbmri_eric/model_fitting.py
> +                        self.warnings.append(warning)
This chunk is large enough to justify extracting it to a separate method.

2022-11-22 05:54 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/bbmri_client.py
> +            raise MolgenisRequestError("{}".format(message))
Yes.

2022-11-22 05:55 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/bbmri_client.py
> +                if "Unknown entity type 'eu_bbmri_eric_also_known_in'" in ex.message:
This statement results in an exception error. 

This check results in 'None' if the entity does not exist:
session.get("sys_md_EntityType", q=f"id=={id_}") so I used this one.

2022-11-22 05:56 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/model_fitting.py
> +        warning = EricWarning(f"Node {self.node.code} has no also_known_in table")
True, I spent some time on figuring out how to let it show up in the summary, unless rewriting a lot of code, I could not find a way. 

The idea you suggest I really like, because the way it was coded now I was not fully happy with it. Especially not having to check the exception message is much better.

I'm not expecting that it is happening more often, so it's no necessary to put it in a separate class. It should also be phased out quite soon, if people from the external servers, of which the server is hosted elsewhere act quickly upon request to change.

2022-11-22 05:56 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/model_fitting.py
> +    """
:-)

2022-11-22 05:56 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/model_fitting.py
> +    def model_fitting(self):
changed

2022-11-22 05:58 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/model_fitting.py
> +            if not set(row.keys()).isdisjoint(set(head_columns)):
Done, I didn't know about this, but it's nice. Loosing the one indentation makes it look much better. I've checked other code if I could use it there also.

2022-11-22 05:59 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/model_fitting.py
> +                        self.warnings.append(warning)
Done.

2022-11-22 06:01 UTC, dtroelofsprins commented on src/molgenis/bbmri_eric/publication_preparer.py
> +    def _model_fitting_node(self, node_data: NodeData, report: ErrorReport):
No, it's also necessary for non-external nodes, for example the ones that use API or file ingest to upload the data in the staging areas. We have to wait for any model changes of the staging area until they've adjusted their code.

2022-11-22 08:53 UTC, tommydeboer requested changes

2022-11-22 08:53 UTC, tommydeboer commented on Pipfile
> +pyhandle = "*"
This shouldn't be here!

2022-11-22 08:53 UTC, tommydeboer commented on src/molgenis/bbmri_eric/model_fitting.py
> +        else:
You can drop the `else` here. Or if you like the `else`, put the `return None` statement inside it. Reads a bit better that way

2022-11-23 13:01 UTC, tommydeboer approved these changes

2022-11-23 13:29 UTC, merged