Ping_fdp, and CRC import scripts and hook for bbmri-testnn added to repo
molgenis/molgenis-py-bbmri-eric pull request #83
Opened 2023-03-10 06:19 UTC by dtroelofsprins

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] Updated CHANGELOG.md

2023-03-10 06:20 UTC, dtroelofsprins commented
![](https://github.trello.services/images/mini-trello-icon.png) [Include all BBMRI-scripts on Github (ping_fdp and get CRC data on BBMRI-NL)](https://trello.com/c/vPlSYqaW/1102-include-all-bbmri-scripts-on-github-pingfdp-and-get-crc-data-on-bbmri-nl)

2023-03-15 11:08 UTC, jelmerveen requested changes
Looks pretty solid to me! Just a few readability points and an optional config addition

2023-03-15 11:08 UTC, jelmerveen commented on scripts/import_CRC_data.py
> +                for unk_type in [
what is 'unk', short for unknown?

2023-03-15 11:08 UTC, jelmerveen commented on scripts/import_CRC_data.py
> +                        lambda x: [i.replace(unk_type, "OTHER") for i in x]
readability is a bit poor. maybe give a better name to x and possibly i

2023-03-15 11:08 UTC, jelmerveen commented on scripts/import_CRC_data.py
> +                        lambda x: [i.replace(unk_type, "OTHER") for i in x]
readability

2023-03-15 11:08 UTC, jelmerveen commented on scripts/import_CRC_data.py
> +                        lambda x: [i.replace(unk_type, "OTHER") for i in x]
readability

2023-03-15 11:08 UTC, jelmerveen commented on scripts/import_CRC_data.py
> +crc_session = EricSession(url="https://crc.molgeniscloud.org")
urls in config?

2023-03-24 10:42 UTC, dtroelofsprins commented on scripts/import_CRC_data.py
> +                for unk_type in [
Yes, indeed, I've replaced it by unknown_type

2023-03-24 10:58 UTC, dtroelofsprins commented on scripts/import_CRC_data.py
> +                        lambda x: [i.replace(unk_type, "OTHER") for i in x]
Replaced x by materials and i by material. Makes more sense now I guess.

2023-03-24 10:58 UTC, dtroelofsprins commented on scripts/import_CRC_data.py
> +                        lambda x: [i.replace(unk_type, "OTHER") for i in x]
Replaces x by types and i by coll_type. Makes more sense now I think.

2023-03-24 10:58 UTC, dtroelofsprins commented on scripts/import_CRC_data.py
> +                        lambda x: [i.replace(unk_type, "OTHER") for i in x]
Replaced x by categories and i by category. Makes more sense now I think.

2023-03-24 11:26 UTC, dtroelofsprins commented on scripts/import_CRC_data.py
> +crc_session = EricSession(url="https://crc.molgeniscloud.org")
I was already struggling with this a bit, as config was not really an option. But coming to think about this again now, I got the idea of using an extra script parameter for this.

2023-03-30 10:03 UTC, merged