feat: add scripts to sync PIDs and Qualities on external servers
molgenis/molgenis-py-bbmri-eric pull request #84
Opened 2023-06-23 09:32 UTC by dtroelofsprins

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] Updated CHANGELOG.md

2023-06-23 11:40 UTC, jelmerveen requested changes

2023-06-23 11:40 UTC, jelmerveen commented on scripts/sync_ERIC_PIDs.py
> +eric_session = Session(url="https://directory.bbmri-eric.eu")
hardcoded url to production?

2023-06-23 11:40 UTC, jelmerveen commented on scripts/sync_ERIC_qualities.py
> +eric_session = Session(url="https://directory.bbmri-eric.eu")
same here

2023-06-23 11:40 UTC, jelmerveen commented on scripts/sync_ERIC_qualities.py
> +eric_session = Session(url="https://directory.bbmri-eric.eu")
maybe use a variable instead.

2023-06-26 05:31 UTC, dtroelofsprins commented on scripts/sync_ERIC_qualities.py
> +eric_session = Session(url="https://directory.bbmri-eric.eu")
You are totally right, replaced the hard-coded URL in both scripts by a parameter

2023-06-27 06:56 UTC, jelmerveen commented on scripts/sync_ERIC_PIDs.py
> +        super(ExtendedSession, self).__init__(*args, **kwargs)
Just curious: Why do you need to pass the class as an argument for super?

2023-06-28 05:23 UTC, dtroelofsprins commented on scripts/sync_ERIC_PIDs.py
> +        super(ExtendedSession, self).__init__(*args, **kwargs)
To be honest: it's a copy paste from other code (developed by Tommy). Did a bit of reading and you are right, there is no need for it, it's equivalent to the parameterless super() call.

2023-06-29 05:34 UTC, dtroelofsprins commented on scripts/sync_ERIC_qualities.py
> +eric_session = Session(url="https://directory.bbmri-eric.eu")
Remove the subclass argument

2023-06-30 05:50 UTC, dtroelofsprins commented on scripts/sync_ERIC_PIDs.py
> +        super(ExtendedSession, self).__init__(*args, **kwargs)
Removed the subclass argument

2023-07-03 06:59 UTC, jelmerveen approved these changes

2023-07-03 07:09 UTC, merged